/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cgpa.program;

/**
 *
 * @author Bhushan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s6 = new javax.swing.JTextField();
        SUBJECT3 = new javax.swing.JTextField();
        SUBJECT4 = new javax.swing.JTextField();
        SUBJECT5 = new javax.swing.JTextField();
        SUBJECT6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        avg = new javax.swing.JTextField();
        SUBJECT2 = new javax.swing.JTextField();
        SUBJECT1 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        s5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CGPA CALCULATOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 455, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUBJECT 1:");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel2.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 194, 132, 77));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUBJECT 5:");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel3.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel3.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 526, 132, 77));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SUBJECT 4:");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel4.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel4.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 443, 132, 77));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SUBJECT 3:");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel5.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel5.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 132, 77));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUBJECT 2:");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel6.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 277, 132, 77));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SUBJECT 6:");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel7.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel7.setPreferredSize(new java.awt.Dimension(130, 40));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 609, 132, 77));

        s6.setEditable(false);
        s6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 71, 77));

        SUBJECT3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBJECT3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SUBJECT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 360, 71, 77));

        SUBJECT4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBJECT4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SUBJECT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 443, 71, 77));

        SUBJECT5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBJECT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SUBJECT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 526, 71, 77));

        SUBJECT6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBJECT6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SUBJECT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 609, 71, 77));

        jButton1.setText("CALCULATE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 140, 60));

        avg.setEditable(false);
        avg.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        avg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgActionPerformed(evt);
            }
        });
        getContentPane().add(avg, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 170, 70));

        SUBJECT2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBJECT2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SUBJECT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 277, 71, 77));

        SUBJECT1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBJECT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(SUBJECT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 71, 77));

        s1.setEditable(false);
        s1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 71, 77));

        s2.setEditable(false);
        s2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 71, 77));

        s3.setEditable(false);
        s3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 71, 77));

        s4.setEditable(false);
        s4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 71, 77));

        s5.setEditable(false);
        s5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        getContentPane().add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 71, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AVERAGE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CGPA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 80, 30));

        gpa.setEditable(false);
        gpa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaActionPerformed(evt);
            }
        });
        getContentPane().add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 170, 70));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MARKS/100");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GRADES");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 146, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Calculates all the score
        
        String subject1Score, subject2Score, subject3Score, subject4Score, subject5Score,subject6Score;
        float average;
        float cgpa=0;
        subject1Score = SUBJECT1.getText();
        subject2Score = SUBJECT2.getText();
        subject3Score = SUBJECT3.getText();
        subject4Score = SUBJECT4.getText();
        subject5Score = SUBJECT5.getText();
        subject6Score = SUBJECT6.getText();
        
        float SUBJECT1 = Float.parseFloat(subject1Score);
        float SUBJECT2 = Float.parseFloat(subject2Score);
        float SUBJECT3 = Float.parseFloat(subject3Score);
        float SUBJECT4 = Float.parseFloat(subject4Score);
        float SUBJECT5 = Float.parseFloat(subject5Score);
        float SUBJECT6 = Float.parseFloat(subject6Score);
        
        
        average = (SUBJECT1 + SUBJECT2 + SUBJECT3 + SUBJECT4 + SUBJECT5 + SUBJECT6)/6;
        
        //SUBJECT1
        if(SUBJECT1 >= 90){
            s1.setText("A+");
            cgpa= cgpa + 10.0f;  
        }
        else if(SUBJECT1 >= 85 && SUBJECT1<90)
        {
            s1.setText("A");
            cgpa= cgpa + 9.5f;
        }
        else if(SUBJECT1 >= 80 && SUBJECT1<95)
        {
            s1.setText("B+");
            cgpa= cgpa + 9.0f;
        }
        else if(SUBJECT1 >= 75 && SUBJECT1<80)
        {
            s1.setText("B");
            cgpa= cgpa + 8.5f;
        }
        else if(SUBJECT1 >= 70 && SUBJECT1<75)
        {
            s1.setText("C+");         
            cgpa= cgpa + 8.0f;
        }
        else if(SUBJECT1 >= 65 && SUBJECT1<70)
        {
            s1.setText("C");
            cgpa= cgpa + 7.5f;
        }
        else if(SUBJECT1 >= 60 && SUBJECT1<65)
        {
            s1.setText("D+");
            cgpa= cgpa + 7.0f;
        }
         else if(SUBJECT1 >= 50 && SUBJECT1<60)
        {
            s1.setText("D");
            cgpa= cgpa + 6.5f;
        }
        else
        {
            s1.setText("F");
            cgpa= cgpa + 5.0f;
        }
        //SUBJECT2
        if(SUBJECT2 >= 90){
            s2.setText("A+");
            cgpa= cgpa + 10.0f;  
        }
        else if(SUBJECT2 >= 85 && SUBJECT2<90)
        {
            s2.setText("A");
            cgpa= cgpa + 9.5f;
        }
        else if(SUBJECT2 >= 80 && SUBJECT2<95)
        {
            s2.setText("B+");
            cgpa= cgpa + 9.0f;
        }
        else if(SUBJECT2 >= 75 && SUBJECT2<80)
        {
            s2.setText("B");
            cgpa= cgpa + 8.5f;
        }
        else if(SUBJECT2 >= 70 && SUBJECT2<75)
        {
            s2.setText("C+");         
            cgpa= cgpa + 8.0f;
        }
        else if(SUBJECT2 >= 65 && SUBJECT2<70)
        {
            s2.setText("C");
            cgpa= cgpa + 7.5f;
        }
        else if(SUBJECT2 >= 60 && SUBJECT2<65)
        {
            s2.setText("D+");
            cgpa= cgpa + 7.0f;
        }
         else if(SUBJECT2 >= 50 && SUBJECT2<60)
        {
            s2.setText("D");
            cgpa= cgpa + 6.5f;
        }
        else
        {
            s2.setText("F");
            cgpa= cgpa + 5.0f;
        }
        
        //SUBJECT3
        if(SUBJECT3 >= 90){
            s3.setText("A+");
            cgpa= cgpa + 10.0f;  
        }
        else if(SUBJECT3 >= 85 && SUBJECT3<90)
        {
            s3.setText("A");
            cgpa= cgpa + 9.5f;
        }
        else if(SUBJECT3 >= 80 && SUBJECT3<95)
        {
            s3.setText("B+");
            cgpa= cgpa + 9.0f;
        }
        else if(SUBJECT3 >= 75 && SUBJECT3<80)
        {
            s3.setText("B");
            cgpa= cgpa + 8.5f;
        }
        else if(SUBJECT3 >= 70 && SUBJECT3<75)
        {
            s3.setText("C+");         
            cgpa= cgpa + 8.0f;
        }
        else if(SUBJECT3 >= 65 && SUBJECT3<70)
        {
            s3.setText("C");
            cgpa= cgpa + 7.5f;
        }
        else if(SUBJECT3 >= 60 && SUBJECT3<65)
        {
            s3.setText("D+");
            cgpa= cgpa + 7.0f;
        }
         else if(SUBJECT3 >= 50 && SUBJECT3<60)
        {
            s3.setText("D");
            cgpa= cgpa + 6.5f;
        }
        else
        {
            s3.setText("F");
            cgpa= cgpa + 5.0f;
        }
        
        //SUBJECT4
        if(SUBJECT4 >= 90){
            s4.setText("A+");
            cgpa= cgpa + 10.0f;  
        }
        else if(SUBJECT4 >= 85 && SUBJECT4<90)
        {
            s4.setText("A");
            cgpa= cgpa + 9.5f;
        }
        else if(SUBJECT4 >= 80 && SUBJECT4<95)
        {
            s4.setText("B+");
            cgpa= cgpa + 9.0f;
        }
        else if(SUBJECT4 >= 75 && SUBJECT4<80)
        {
            s4.setText("B");
            cgpa= cgpa + 8.5f;
        }
        else if(SUBJECT4 >= 70 && SUBJECT4<75)
        {
            s4.setText("C+");         
            cgpa= cgpa + 8.0f;
        }
        else if(SUBJECT4 >= 65 && SUBJECT4<70)
        {
            s4.setText("C");
            cgpa= cgpa + 7.5f;
        }
        else if(SUBJECT4 >= 60 && SUBJECT4<65)
        {
            s4.setText("D+");
            cgpa= cgpa + 7.0f;
        }
         else if(SUBJECT4 >= 50 && SUBJECT4<60)
        {
            s4.setText("D");
            cgpa= cgpa + 6.5f;
        }
        else
        {
            s4.setText("F");
            cgpa= cgpa + 5.0f;
        }
        
        //SUBJECT5
        if(SUBJECT5 >= 90){
            s5.setText("A+");
            cgpa= cgpa + 10.0f;  
        }
        else if(SUBJECT5 >= 85 && SUBJECT5<90)
        {
            s5.setText("A");
            cgpa= cgpa + 9.5f;
        }
        else if(SUBJECT5 >= 80 && SUBJECT5<95)
        {
            s5.setText("B+");
            cgpa= cgpa + 9.0f;
        }
        else if(SUBJECT5 >= 75 && SUBJECT5<80)
        {
            s5.setText("B");
            cgpa= cgpa + 8.5f;
        }
        else if(SUBJECT5 >= 70 && SUBJECT5<75)
        {
            s5.setText("C+");         
            cgpa= cgpa + 8.0f;
        }
        else if(SUBJECT5 >= 65 && SUBJECT5<70)
        {
            s5.setText("C");
            cgpa= cgpa + 7.5f;
        }
        else if(SUBJECT5 >= 60 && SUBJECT5<65)
        {
            s5.setText("D+");
            cgpa= cgpa + 7.0f;
        }
         else if(SUBJECT5 >= 50 && SUBJECT5<60)
        {
            s5.setText("D");
            cgpa= cgpa + 6.5f;
        }
        else
        {
            s5.setText("F");
            cgpa= cgpa + 5.0f;
        }
       //SUBJECT6
        if(SUBJECT6 >= 90){
            s6.setText("A+");
            cgpa= cgpa + 10.0f;  
        }
        else if(SUBJECT6 >= 85 && SUBJECT6<90)
        {
            s6.setText("A");
            cgpa= cgpa + 9.5f;
        }
        else if(SUBJECT6 >= 80 && SUBJECT6<95)
        {
            s6.setText("B+");
            cgpa= cgpa + 9.0f;
        }
        else if(SUBJECT6 >= 75 && SUBJECT6<80)
        {
            s6.setText("B");
            cgpa= cgpa + 8.5f;
        }
        else if(SUBJECT6 >= 70 && SUBJECT6<75)
        {
            s6.setText("C+");         
            cgpa= cgpa + 8.0f;
        }
        else if(SUBJECT6 >= 65 && SUBJECT6<70)
        {
            s6.setText("C");
            cgpa= cgpa + 7.5f;
        }
        else if(SUBJECT6 >= 60 && SUBJECT6<65)
        {
            s1.setText("D+");
            cgpa= cgpa + 7.0f;
        }
         else if(SUBJECT6 >= 50 && SUBJECT6<60)
        {
            s6.setText("D");
            cgpa= cgpa + 6.5f;
        }
        else
        {
            s6.setText("F");
            cgpa= cgpa + 5.0f;
        }
        
        cgpa = cgpa/6;
        
        gpa.setText(Float.toString(cgpa));
        avg.setText(Float.toString(average));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void avgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s5ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SUBJECT1;
    private javax.swing.JTextField SUBJECT2;
    private javax.swing.JTextField SUBJECT3;
    private javax.swing.JTextField SUBJECT4;
    private javax.swing.JTextField SUBJECT5;
    private javax.swing.JTextField SUBJECT6;
    private javax.swing.JTextField avg;
    private javax.swing.JTextField gpa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    // End of variables declaration//GEN-END:variables
}
